"""
MT5 Bridge — pilote MT5 Desktop depuis un HTTP local.

Architecture :
    Scalping Radar (EC2)
        └── POST /order ──► Bridge HTTP (ce fichier, tourne sur le PC Windows)
                              └── MetaTrader5 package ──► MT5 Desktop (local)

Sécurité :
- Bind sur 127.0.0.1 par défaut (pas exposé sur le réseau).
- Tous les endpoints sensibles demandent l'en-tête X-API-Key.
- PAPER_MODE=true par défaut : aucun ordre réel n'est envoyé à MT5.
- Les credentials sont lus depuis .env (gitignored).
"""

import logging
import json
import os
import secrets
import sqlite3
import threading
import time
from datetime import datetime, timezone, date
from functools import wraps
from pathlib import Path

import MetaTrader5 as mt5
from dotenv import load_dotenv
from flask import Flask, jsonify, request

load_dotenv()

# ─── Configuration ──────────────────────────────────────────────────
MT5_LOGIN = int(os.getenv("MT5_LOGIN", "0"))
MT5_PASSWORD = os.getenv("MT5_PASSWORD", "")
MT5_SERVER = os.getenv("MT5_SERVER", "MetaQuotes-Demo")
BRIDGE_API_KEY = os.getenv("BRIDGE_API_KEY", "")
PAPER_MODE = os.getenv("PAPER_MODE", "true").lower() in ("1", "true", "yes", "on")
MAX_LOT = float(os.getenv("MAX_LOT", "0.1"))
# Caps par asset class en plus du MAX_LOT global. JSON env var, ex:
# MAX_LOT_PER_CLASS='{"forex":0.1,"metal":0.1,"crypto":0.01,"equity_index":0.05,"energy":0.1}'
# Le lot final = min(MAX_LOT, MAX_LOT_PER_CLASS[class]). Une classe absente
# tombe sur MAX_LOT global (pas de cap supplémentaire).
try:
    _max_lot_per_class_raw = os.getenv("MAX_LOT_PER_CLASS", "").strip()
    MAX_LOT_PER_CLASS = json.loads(_max_lot_per_class_raw) if _max_lot_per_class_raw else {}
    if not isinstance(MAX_LOT_PER_CLASS, dict):
        MAX_LOT_PER_CLASS = {}
except (json.JSONDecodeError, TypeError):
    MAX_LOT_PER_CLASS = {}
LISTEN_HOST = os.getenv("LISTEN_HOST", "127.0.0.1")
LISTEN_PORT = int(os.getenv("LISTEN_PORT", "8787"))
BREAKEVEN_TRIGGER_PCT = float(os.getenv("BREAKEVEN_TRIGGER_PCT", "50"))
MONITOR_INTERVAL_SEC = int(os.getenv("MONITOR_INTERVAL_SEC", "5"))
# Rails LIVE
MAX_DAILY_LOSS_PCT = float(os.getenv("MAX_DAILY_LOSS_PCT", "3.0"))
MAX_OPEN_POSITIONS = int(os.getenv("MAX_OPEN_POSITIONS", "3"))
DEDUP_WINDOW_SEC = int(os.getenv("DEDUP_WINDOW_SEC", "300"))
DEVIATION_POINTS = int(os.getenv("DEVIATION_POINTS", "20"))
MAGIC_NUMBER = int(os.getenv("MAGIC_NUMBER", "20260419"))
TRADING_HOURS_UTC = os.getenv("TRADING_HOURS_UTC", "").strip()
# Partial close + trailing
PARTIAL_CLOSE_PCT = float(os.getenv("PARTIAL_CLOSE_PCT", "50"))
TRAIL_DISTANCE_POINTS = int(os.getenv("TRAIL_DISTANCE_POINTS", "150"))

# Génère une clé si absente (affichée au démarrage pour copie dans le client)
if not BRIDGE_API_KEY:
    BRIDGE_API_KEY = secrets.token_urlsafe(24)
    _KEY_AUTOGENERATED = True
else:
    _KEY_AUTOGENERATED = False

# ─── Logging ────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler("bridge.log", encoding="utf-8"),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger("bridge")

# ─── App Flask ──────────────────────────────────────────────────────
app = Flask(__name__)


def require_api_key(f):
    """Décorateur : exige l'en-tête X-API-Key, comparé en constant-time."""
    @wraps(f)
    def wrapped(*args, **kwargs):
        provided = request.headers.get("X-API-Key", "")
        if not secrets.compare_digest(provided, BRIDGE_API_KEY):
            return jsonify({"error": "Invalid or missing X-API-Key"}), 401
        return f(*args, **kwargs)
    return wrapped


# ─── Connexion MT5 ──────────────────────────────────────────────────

def ensure_mt5_connected() -> bool:
    """Initialise MT5 si pas déjà fait. Retourne True si connecté."""
    # Si déjà initialisé et un compte est attaché, on ne reconnecte pas.
    if mt5.account_info() is not None:
        return True
    if not mt5.initialize(
        login=MT5_LOGIN, password=MT5_PASSWORD, server=MT5_SERVER
    ):
        err = mt5.last_error()
        logger.error(f"mt5.initialize() a échoué : {err}")
        return False
    info = mt5.account_info()
    if info is None:
        err = mt5.last_error()
        logger.error(f"account_info() None après init : {err}")
        return False
    logger.info(
        f"MT5 connecté : login={info.login} server={MT5_SERVER} "
        f"balance={info.balance} {info.currency}"
    )
    return True


def resolve_symbol(pair_str: str):
    """Traduit un format 'EUR/USD' vers le symbole réel du broker.

    MetaQuotes-Demo utilise typiquement 'EURUSD', mais les brokers peuvent
    suffixer (.c, .m, .pro, etc.). On tente plusieurs variantes et on
    retourne la première qui existe et est sélectionnable.
    """
    base = pair_str.replace("/", "")
    candidates = [
        pair_str,        # EUR/USD littéral
        base,            # EURUSD
        base + ".c",
        base + ".m",
        base + "m",
        base + ".pro",
        base + ".raw",
    ]
    for c in candidates:
        info = mt5.symbol_info(c)
        if info is None:
            continue
        if not info.visible:
            if not mt5.symbol_select(c, True):
                continue
        return c
    return None


# ─── Audit DB (SQLite local, persiste entre redémarrages) ──────────

_DB_PATH = Path(__file__).parent / "bridge_audit.db"
_db_lock = threading.Lock()


def _db_init() -> None:
    """Crée la table d'audit si elle n'existe pas + migre les colonnes manquantes."""
    with sqlite3.connect(_DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS orders (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                mode TEXT NOT NULL,       -- 'paper' | 'live'
                status TEXT NOT NULL,     -- 'filled' | 'rejected' | 'blocked' | 'error' | 'closed'
                pair TEXT,
                symbol TEXT,
                direction TEXT,
                lots REAL,
                entry REAL,
                sl REAL,
                tp REAL,
                risk_money REAL,
                ticket INTEGER,
                retcode INTEGER,
                message TEXT,
                client_comment TEXT
            );
        """)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at);")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_orders_ticket ON orders(ticket);")
        # Migration : ajoute exit_price + pnl + confidence si DB ancienne
        cols = [r[1] for r in conn.execute("PRAGMA table_info(orders)").fetchall()]
        if "exit_price" not in cols:
            conn.execute("ALTER TABLE orders ADD COLUMN exit_price REAL")
        if "pnl" not in cols:
            conn.execute("ALTER TABLE orders ADD COLUMN pnl REAL")
        if "confidence" not in cols:
            conn.execute("ALTER TABLE orders ADD COLUMN confidence REAL")
        conn.commit()


def _db_log_order(**fields) -> None:
    """Insère une ligne d'audit. Tous les champs sont optionnels (sauf status/mode)."""
    fields.setdefault("created_at", datetime.now(timezone.utc).isoformat())
    cols = list(fields.keys())
    placeholders = ",".join("?" * len(cols))
    sql = f"INSERT INTO orders ({','.join(cols)}) VALUES ({placeholders})"
    try:
        with _db_lock, sqlite3.connect(_DB_PATH) as conn:
            conn.execute(sql, tuple(fields.values()))
            conn.commit()
    except Exception as e:
        logger.warning(f"audit DB write failed: {e}")


# ─── Rails de sécurité LIVE ─────────────────────────────────────────

# Balance de début de journée (pour le drawdown) — réinitialisée à chaque jour.
_start_of_day_balance: float | None = None
_start_of_day_date: date | None = None


def _refresh_start_of_day() -> None:
    """Relit la balance au début de chaque jour trading."""
    global _start_of_day_balance, _start_of_day_date
    today = date.today()
    if _start_of_day_date != today:
        info = mt5.account_info()
        if info is not None:
            _start_of_day_balance = info.balance
            _start_of_day_date = today
            logger.info(
                f"Start-of-day balance = {_start_of_day_balance:.2f} "
                f"(date={today.isoformat()})"
            )


def _parse_trading_hours(window: str) -> list[tuple[int, int]]:
    """Parse 'HH:MM-HH:MM,HH:MM-HH:MM' en [(minutes_from_midnight_start, end)]."""
    ranges = []
    if not window:
        return ranges
    for chunk in window.split(","):
        chunk = chunk.strip()
        if "-" not in chunk:
            continue
        a, b = chunk.split("-", 1)
        try:
            ah, am = [int(x) for x in a.split(":")]
            bh, bm = [int(x) for x in b.split(":")]
            ranges.append((ah * 60 + am, bh * 60 + bm))
        except ValueError:
            continue
    return ranges


def _in_trading_hours() -> bool:
    """Vrai si TRADING_HOURS_UTC est vide OU si maintenant (UTC) est dans une plage."""
    if not TRADING_HOURS_UTC:
        return True
    now_utc = datetime.now(timezone.utc)
    now_min = now_utc.hour * 60 + now_utc.minute
    for start, end in _parse_trading_hours(TRADING_HOURS_UTC):
        if start <= now_min <= end:
            return True
    return False


def _check_safety_gates(mt5_symbol: str, direction: str) -> tuple[bool, str]:
    """Vérifie tous les garde-fous avant d'envoyer un ordre LIVE.

    Retourne (ok, reason). Si ok=False, 'reason' est la raison du blocage
    (à remonter dans la réponse HTTP et loggée dans l'audit DB).
    """
    if not _in_trading_hours():
        return False, f"Outside TRADING_HOURS_UTC ({TRADING_HOURS_UTC})"

    info = mt5.account_info()
    if info is None:
        return False, "Cannot read account_info"

    # Drawdown journalier
    _refresh_start_of_day()
    if _start_of_day_balance is not None:
        loss_limit = _start_of_day_balance * MAX_DAILY_LOSS_PCT / 100.0
        current_loss = _start_of_day_balance - info.equity
        if current_loss >= loss_limit:
            return False, (
                f"Daily drawdown reached: loss={current_loss:.2f} "
                f">= limit={loss_limit:.2f} ({MAX_DAILY_LOSS_PCT}% of "
                f"{_start_of_day_balance:.2f})"
            )

    # Max positions ouvertes
    positions = mt5.positions_get() or []
    if len(positions) >= MAX_OPEN_POSITIONS:
        return False, (
            f"Max open positions reached: {len(positions)} >= {MAX_OPEN_POSITIONS}"
        )

    # Dedup : refuse si même symbole + même sens ouvert depuis < DEDUP_WINDOW_SEC
    now_ts = int(datetime.now(timezone.utc).timestamp())
    wanted_type = mt5.POSITION_TYPE_BUY if direction == "buy" else mt5.POSITION_TYPE_SELL
    for p in positions:
        if p.symbol == mt5_symbol and p.type == wanted_type:
            if now_ts - p.time < DEDUP_WINDOW_SEC:
                age = now_ts - p.time
                return False, (
                    f"Duplicate: {direction} {mt5_symbol} already open (age {age}s "
                    f"< DEDUP_WINDOW_SEC={DEDUP_WINDOW_SEC}s, ticket #{p.ticket})"
                )

    return True, "OK"


# Bitmask des filling modes (certaines versions du package MT5 n'exposent pas
# les constantes mt5.SYMBOL_FILLING_* → on hardcode depuis la doc MQL5).
_SYMBOL_FILLING_FOK = 1
_SYMBOL_FILLING_IOC = 2
_SYMBOL_FILLING_BOC = 4


def _pick_filling_mode(symbol: str) -> int:
    """Choisit le filling mode compatible avec le broker pour ce symbole.

    symbol_info.filling_mode est un bitmask des modes supportés.
    On prend le premier qui matche : IOC > FOK > RETURN."""
    try:
        info = mt5.symbol_info(symbol)
        if info is None:
            return mt5.ORDER_FILLING_IOC
        fm = getattr(info, "filling_mode", 0) or 0
        if fm & _SYMBOL_FILLING_IOC:
            return mt5.ORDER_FILLING_IOC
        if fm & _SYMBOL_FILLING_FOK:
            return mt5.ORDER_FILLING_FOK
        return mt5.ORDER_FILLING_RETURN
    except Exception as e:
        logger.warning(f"_pick_filling_mode fallback (IOC): {e}")
        return mt5.ORDER_FILLING_IOC


def _send_market_order(symbol: str, direction: str, lots: float, sl: float, tp: float, comment: str) -> dict:
    """Envoie un ordre MARKET à MT5. Retourne un dict {ok, ticket, retcode, message}."""
    tick = mt5.symbol_info_tick(symbol)
    if tick is None:
        return {"ok": False, "message": f"No tick data for {symbol}"}

    price = tick.ask if direction == "buy" else tick.bid
    order_type = mt5.ORDER_TYPE_BUY if direction == "buy" else mt5.ORDER_TYPE_SELL

    req = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": lots,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "deviation": DEVIATION_POINTS,
        "magic": MAGIC_NUMBER,
        "comment": comment[:30],  # MT5 limite le comment
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": _pick_filling_mode(symbol),
    }
    result = mt5.order_send(req)
    if result is None:
        return {"ok": False, "message": f"order_send returned None: {mt5.last_error()}"}
    return {
        "ok": result.retcode == mt5.TRADE_RETCODE_DONE,
        "ticket": result.order,
        "retcode": result.retcode,
        "message": result.comment,
        "price": result.price,
        "volume": result.volume,
    }


def _close_position(p) -> dict:
    """Ferme une position ouverte en envoyant un ordre opposé."""
    opposite = mt5.ORDER_TYPE_SELL if p.type == mt5.POSITION_TYPE_BUY else mt5.ORDER_TYPE_BUY
    tick = mt5.symbol_info_tick(p.symbol)
    if tick is None:
        return {"ok": False, "ticket": p.ticket, "message": "no tick"}
    price = tick.bid if p.type == mt5.POSITION_TYPE_BUY else tick.ask
    req = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": p.symbol,
        "volume": p.volume,
        "type": opposite,
        "position": p.ticket,
        "price": price,
        "deviation": DEVIATION_POINTS,
        "magic": MAGIC_NUMBER,
        "comment": f"kill-{p.ticket}"[:30],
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": _pick_filling_mode(p.symbol),
    }
    r = mt5.order_send(req)
    if r is None:
        return {"ok": False, "ticket": p.ticket, "message": str(mt5.last_error())}
    return {
        "ok": r.retcode == mt5.TRADE_RETCODE_DONE,
        "ticket": p.ticket,
        "retcode": r.retcode,
        "message": r.comment,
    }


# ─── Monitor de positions (background thread) ──────────────────────
#
# Tourne en continu, regarde toutes les N secondes les positions ouvertes
# et applique le break-even (SL déplacé à entry + 1 pip) dès que le prix
# a parcouru BREAKEVEN_TRIGGER_PCT % du chemin vers TP1.
#
# En PAPER_MODE : log seulement ce qui SERAIT fait (utile pour observer
# la logique avant de passer en LIVE).
# En LIVE : envoie un mt5.order_send(TRADE_ACTION_SLTP) pour modifier le SL.
# ────────────────────────────────────────────────────────────────────

_monitor_stop = threading.Event()
_breakeven_applied: set[int] = set()  # tickets déjà passés en BE
_last_known_tickets: set[int] = set()  # positions ouvertes au dernier passage du monitor

# Métadonnées par ticket : TP1, TP2, état partial-close, trailing
# Stockées en mémoire. Perdues au redémarrage du bridge — acceptable puisque
# les positions existantes gardent leur SL/TP MT5 natifs comme filet.
_position_meta: dict[int, dict] = {}
_meta_lock = threading.Lock()


def _register_position_meta(ticket: int, tp1: float, tp2: float | None) -> None:
    """Mémorise TP1/TP2 pour un ordre qui vient d'être passé.
    Appelé depuis /order après un order_send réussi en LIVE."""
    with _meta_lock:
        _position_meta[ticket] = {
            "tp1": tp1,
            "tp2": tp2 if (tp2 is not None and tp2 > 0) else None,
            "partial_closed": False,
            "trailing_active": False,
        }


def _cleanup_closed_meta(open_tickets: set[int]) -> None:
    """Purge les meta des tickets qui ne sont plus ouverts."""
    with _meta_lock:
        for t in list(_position_meta.keys()):
            if t not in open_tickets:
                del _position_meta[t]


def _pip_size(symbol: str) -> float:
    """Taille d'un pip selon la paire (JPY ≈ 0.01, autres = 0.0001).
    XAU/XAG/crypto utilisent 0.01 ou 0.001 — on reste simple pour l'instant."""
    if "JPY" in symbol.upper():
        return 0.01
    if "XAU" in symbol.upper() or "XAG" in symbol.upper():
        return 0.01
    return 0.0001


def _maybe_move_to_breakeven(p) -> None:
    """Si la position a atteint X% du chemin vers TP1, déplace le SL à BE.
    Idempotent via _breakeven_applied (dedup par ticket)."""
    if p.ticket in _breakeven_applied:
        return
    if p.tp == 0 or p.sl == 0:
        return  # pas de SL/TP défini → rien à faire

    pip = _pip_size(p.symbol)
    if p.type == mt5.POSITION_TYPE_BUY:
        tp_distance = p.tp - p.price_open
        current_progress = p.price_current - p.price_open
        if tp_distance <= 0:
            return
        if current_progress / tp_distance < BREAKEVEN_TRIGGER_PCT / 100.0:
            return
        new_sl = p.price_open + pip
        if new_sl <= p.sl:
            return  # SL déjà mieux placé
    else:  # SELL
        tp_distance = p.price_open - p.tp
        current_progress = p.price_open - p.price_current
        if tp_distance <= 0:
            return
        if current_progress / tp_distance < BREAKEVEN_TRIGGER_PCT / 100.0:
            return
        new_sl = p.price_open - pip
        if new_sl >= p.sl:
            return

    if PAPER_MODE:
        logger.info(
            f"[PAPER BE] pos#{p.ticket} {p.symbol} {p.volume}L "
            f"progress={current_progress / tp_distance * 100:.0f}% "
            f"SL {p.sl:.5f} → {new_sl:.5f}"
        )
        _breakeven_applied.add(p.ticket)
        return

    # LIVE — modifie le SL via TRADE_ACTION_SLTP
    request = {
        "action": mt5.TRADE_ACTION_SLTP,
        "position": p.ticket,
        "symbol": p.symbol,
        "sl": new_sl,
        "tp": p.tp,
    }
    result = mt5.order_send(request)
    if result and result.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(
            f"[LIVE BE] pos#{p.ticket} {p.symbol} SL → {new_sl:.5f} ✓"
        )
        _breakeven_applied.add(p.ticket)
    else:
        rc = getattr(result, "retcode", "?")
        cm = getattr(result, "comment", "?")
        logger.warning(
            f"[LIVE BE FAIL] pos#{p.ticket} retcode={rc} comment={cm}"
        )


def _maybe_partial_close_and_trail(p) -> None:
    """Gestion active d'une position : partial close à TP1 + trailing stop.

    Flux :
    1. Si position pas encore en partial-close ET prix a atteint TP1 :
       - ferme PARTIAL_CLOSE_PCT % du volume (ordre opposé partiel)
       - modifie le reste : SL → entry (BE), TP → TP2 (si fourni)
       - active le trailing
    2. Si trailing actif :
       - remonte le SL à price_current ± TRAIL_DISTANCE_POINTS selon direction
       - mais seulement si ça améliore le SL actuel
    """
    meta = _position_meta.get(p.ticket)
    if meta is None:
        return  # position pas tracée (ouverte avant le bridge, ou en manuel)

    info = mt5.symbol_info(p.symbol)
    if info is None or info.point <= 0:
        return

    # ─── Phase 1 : partial close à TP1 ─────────────────────────
    if not meta["partial_closed"]:
        tp1 = meta.get("tp1")
        if tp1 is None or tp1 <= 0:
            return  # pas de TP1 → on ne fait rien
        reached_tp1 = (
            p.price_current >= tp1 if p.type == mt5.POSITION_TYPE_BUY
            else p.price_current <= tp1
        )
        if not reached_tp1:
            return

        # Taille à fermer = PARTIAL_CLOSE_PCT % du volume, arrondi au step broker
        close_volume = round(
            p.volume * PARTIAL_CLOSE_PCT / 100.0 / info.volume_step
        ) * info.volume_step
        remaining = round(p.volume - close_volume, 3)
        # Garde-fous : si les 2 portions tombent sous volume_min, skip
        if close_volume < info.volume_min or remaining < info.volume_min:
            logger.info(
                f"pos#{p.ticket}: volume trop petit pour partial close "
                f"(close={close_volume}, remaining={remaining}, "
                f"min={info.volume_min}) — laisse courir entier"
            )
            meta["partial_closed"] = True  # évite de re-checker
            meta["trailing_active"] = bool(TRAIL_DISTANCE_POINTS)
            return

        if PAPER_MODE:
            logger.info(
                f"[PAPER PARTIAL] pos#{p.ticket} close {close_volume}L / keep {remaining}L "
                f"+ move SL→BE + TP→{meta.get('tp2') or 'same'}"
            )
            meta["partial_closed"] = True
            meta["trailing_active"] = bool(TRAIL_DISTANCE_POINTS)
            return

        # LIVE : envoie un ordre opposite partiel
        opposite = mt5.ORDER_TYPE_SELL if p.type == mt5.POSITION_TYPE_BUY else mt5.ORDER_TYPE_BUY
        tick = mt5.symbol_info_tick(p.symbol)
        if tick is None:
            return
        close_price = tick.bid if p.type == mt5.POSITION_TYPE_BUY else tick.ask
        close_req = {
            "action": mt5.TRADE_ACTION_DEAL,
            "symbol": p.symbol,
            "volume": close_volume,
            "type": opposite,
            "position": p.ticket,
            "price": close_price,
            "deviation": DEVIATION_POINTS,
            "magic": MAGIC_NUMBER,
            "comment": f"partial-{p.ticket}"[:30],
            "type_time": mt5.ORDER_TIME_GTC,
            "type_filling": _pick_filling_mode(p.symbol),
        }
        r = mt5.order_send(close_req)
        if r is None or r.retcode != mt5.TRADE_RETCODE_DONE:
            rc = getattr(r, "retcode", "?")
            cm = getattr(r, "comment", "?")
            logger.warning(f"[LIVE PARTIAL FAIL] pos#{p.ticket} retcode={rc} {cm}")
            return

        logger.info(
            f"[LIVE PARTIAL ✓] pos#{p.ticket} closed {close_volume}L "
            f"@ {close_price} ({PARTIAL_CLOSE_PCT}%)"
        )

        # Modifie le reste : SL → entry (BE), TP → TP2 (si dispo, sinon laisse TP1)
        new_tp = meta.get("tp2") or p.tp
        new_sl = p.price_open  # break-even exact (pas entry+1pip ici : trailing suivra)
        modify_req = {
            "action": mt5.TRADE_ACTION_SLTP,
            "position": p.ticket,
            "symbol": p.symbol,
            "sl": new_sl,
            "tp": new_tp,
        }
        r2 = mt5.order_send(modify_req)
        if r2 and r2.retcode == mt5.TRADE_RETCODE_DONE:
            logger.info(
                f"[LIVE PARTIAL BE] pos#{p.ticket} SL→{new_sl:.5f} TP→{new_tp:.5f}"
            )
        else:
            logger.warning(
                f"[LIVE PARTIAL BE FAIL] pos#{p.ticket} "
                f"retcode={getattr(r2, 'retcode', '?')}"
            )

        meta["partial_closed"] = True
        meta["trailing_active"] = bool(TRAIL_DISTANCE_POINTS)
        _breakeven_applied.add(p.ticket)  # pas besoin de BE classique
        return

    # ─── Phase 2 : trailing stop sur le reste ──────────────────
    if not meta["trailing_active"] or TRAIL_DISTANCE_POINTS <= 0:
        return
    trail_distance = TRAIL_DISTANCE_POINTS * info.point
    if p.type == mt5.POSITION_TYPE_BUY:
        new_sl = p.price_current - trail_distance
        if new_sl <= p.sl:
            return  # pas mieux
    else:
        new_sl = p.price_current + trail_distance
        if new_sl >= p.sl:
            return

    if PAPER_MODE:
        logger.info(
            f"[PAPER TRAIL] pos#{p.ticket} SL {p.sl:.5f} → {new_sl:.5f} "
            f"(price={p.price_current:.5f}, distance={TRAIL_DISTANCE_POINTS}pts)"
        )
        return

    # LIVE modify
    req = {
        "action": mt5.TRADE_ACTION_SLTP,
        "position": p.ticket,
        "symbol": p.symbol,
        "sl": new_sl,
        "tp": p.tp,
    }
    r = mt5.order_send(req)
    if r and r.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(f"[LIVE TRAIL] pos#{p.ticket} SL → {new_sl:.5f}")
    else:
        logger.warning(
            f"[LIVE TRAIL FAIL] pos#{p.ticket} retcode={getattr(r, 'retcode', '?')}"
        )


def _log_closed_position(ticket: int) -> None:
    """Quand un ticket disparaît des positions ouvertes, log sa fermeture
    avec exit_price + pnl dans l'audit DB. Lit l'historique MT5 des deals."""
    try:
        # Deals liés à ce ticket (ouvre + clôture). On somme profit+swap+commission.
        deals = mt5.history_deals_get(position=ticket)
        if not deals:
            logger.info(f"[CLOSE] ticket #{ticket} fermé — pas d'historique disponible")
            return
        total_pnl = 0.0
        exit_price = None
        exit_time = None
        symbol = None
        volume = None
        for d in deals:
            total_pnl += (d.profit or 0) + (d.swap or 0) + (d.commission or 0)
            if d.entry == mt5.DEAL_ENTRY_OUT or d.entry == mt5.DEAL_ENTRY_OUT_BY:
                exit_price = d.price
                exit_time = d.time
                symbol = d.symbol
                volume = d.volume
        logger.info(
            f"[CLOSE] ticket #{ticket} {symbol} exit @ {exit_price} "
            f"PnL={total_pnl:+.2f}"
        )
        _db_log_order(
            mode="live",
            status="closed",
            symbol=symbol,
            lots=volume,
            ticket=ticket,
            exit_price=exit_price,
            pnl=round(total_pnl, 2),
            message=f"Closed at {exit_price}" if exit_price else "Closed",
        )
    except Exception as e:
        logger.warning(f"_log_closed_position({ticket}) error: {e}")


def _position_monitor_loop():
    """Boucle principale du monitor. S'arrête via _monitor_stop.set()."""
    global _last_known_tickets
    logger.info(
        f"Monitor de positions démarré "
        f"(interval={MONITOR_INTERVAL_SEC}s, "
        f"BE={BREAKEVEN_TRIGGER_PCT}%, "
        f"partial={PARTIAL_CLOSE_PCT}%, "
        f"trail={TRAIL_DISTANCE_POINTS}pts)"
    )
    while not _monitor_stop.is_set():
        try:
            if ensure_mt5_connected():
                positions = mt5.positions_get() or []
                open_tickets = {p.ticket for p in positions}
                # Détection des fermetures : tickets présents au dernier tour
                # mais plus là maintenant. Log l'event dans l'audit DB.
                closed_tickets = _last_known_tickets - open_tickets
                for t in closed_tickets:
                    _log_closed_position(t)
                _last_known_tickets = open_tickets
                # Purge les tickets fermés des sets de tracking
                _breakeven_applied.intersection_update(open_tickets)
                _cleanup_closed_meta(open_tickets)
                for p in positions:
                    # Gestion active d'abord (partial + trail) pour les positions
                    # que nous avons ouvertes et tracées.
                    _maybe_partial_close_and_trail(p)
                    # Break-even fallback pour les positions sans meta (ex: anciens)
                    if p.ticket not in _position_meta:
                        _maybe_move_to_breakeven(p)
        except Exception as e:
            logger.warning(f"Monitor loop error: {e}")
        if _monitor_stop.wait(timeout=MONITOR_INTERVAL_SEC):
            break
    logger.info("Monitor de positions arrêté")


# ─── Endpoints ──────────────────────────────────────────────────────

@app.route("/health", methods=["GET"])
def health():
    """Ping public (pas d'auth). Utile pour vérifier que le bridge tourne."""
    connected = ensure_mt5_connected()
    return jsonify({
        "ok": connected,
        "paper_mode": PAPER_MODE,
        "server": MT5_SERVER,
        "login": MT5_LOGIN,
        "mt5_version": mt5.__version__,
        "max_lot": MAX_LOT,
        "max_lot_per_class": MAX_LOT_PER_CLASS,
    })


@app.route("/account", methods=["GET"])
@require_api_key
def account():
    """État du compte : balance, equity, positions ouvertes."""
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503
    info = mt5.account_info()
    if info is None:
        return jsonify({"error": "no account info"}), 503
    return jsonify({
        "login": info.login,
        "balance": info.balance,
        "equity": info.equity,
        "profit": info.profit,
        "margin": info.margin,
        "margin_free": info.margin_free,
        "currency": info.currency,
        "leverage": info.leverage,
        "positions_count": mt5.positions_total() or 0,
    })


@app.route("/tick/<path:pair>", methods=["GET"])
@require_api_key
def tick(pair):
    """Prix bid/ask courant d'une paire. Utile pour valider SL/TP avant un ordre."""
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503
    sym = resolve_symbol(pair)
    if not sym:
        return jsonify({"error": f"symbol not found for {pair}"}), 404
    t = mt5.symbol_info_tick(sym)
    if t is None:
        return jsonify({"error": f"no tick for {sym}"}), 503
    info = mt5.symbol_info(sym)
    return jsonify({
        "pair": pair,
        "symbol": sym,
        "bid": t.bid,
        "ask": t.ask,
        "spread": round((t.ask - t.bid) / info.point) if info else None,
        "stops_level_points": info.trade_stops_level if info else None,
        "point": info.point if info else None,
        "time": datetime.fromtimestamp(t.time, tz=timezone.utc).isoformat(),
    })


@app.route("/symbols", methods=["GET"])
@require_api_key
def symbols():
    """Liste les symboles disponibles sur le compte.

    Query params :
      ?query=BTC   filtre substring insensible a la casse
      ?limit=500   cap sur le nombre de resultats (defaut : pas de cap)
    """
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503
    all_syms = mt5.symbols_get() or []
    names = [s.name for s in all_syms]
    query = request.args.get("query", "").strip().upper()
    if query:
        names = [n for n in names if query in n.upper()]
    limit_str = request.args.get("limit", "").strip()
    if limit_str:
        try:
            names = names[: int(limit_str)]
        except ValueError:
            pass
    return jsonify({"count": len(names), "symbols": names})


@app.route("/positions", methods=["GET"])
@require_api_key
def positions():
    """Positions ouvertes en temps réel."""
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503
    pos_list = mt5.positions_get() or []
    return jsonify({
        "count": len(pos_list),
        "positions": [
            {
                "ticket": p.ticket,
                "symbol": p.symbol,
                "type": "buy" if p.type == mt5.POSITION_TYPE_BUY else "sell",
                "volume": p.volume,
                "price_open": p.price_open,
                "price_current": p.price_current,
                "sl": p.sl,
                "tp": p.tp,
                "profit": p.profit,
                "time": datetime.fromtimestamp(p.time, tz=timezone.utc).isoformat(),
                "comment": p.comment,
            }
            for p in pos_list
        ],
    })


@app.route("/deals", methods=["GET"])
@require_api_key
def deals():
    """Retourne le deal de fermeture (DEAL_ENTRY_OUT) pour un ticket donné.

    Utilisé par le radar (_reconcile_open_trades) pour mettre à jour
    personal_trades.status/exit_price/pnl quand MT5 a fermé la position
    naturellement (SL/TP touchés) sans passer par /kill ni /close.

    Réponses :
    - closed=true  : position fermée, exit_price + pnl + closed_at renseignés
    - closed=false : position encore ouverte côté MT5
    - closed=null  : aucun deal trouvé (ticket inconnu ou history purgée)
    """
    try:
        ticket = int(request.args.get("ticket", 0))
    except (TypeError, ValueError):
        return jsonify({"error": "ticket must be int"}), 400
    if ticket <= 0:
        return jsonify({"error": "ticket required"}), 400

    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503

    pos = mt5.positions_get(ticket=ticket)
    if pos:
        return jsonify({"ticket": ticket, "closed": False})

    deals_list = mt5.history_deals_get(position=ticket) or []
    out_deal = next(
        (d for d in deals_list if d.entry == mt5.DEAL_ENTRY_OUT), None
    )
    if out_deal is None:
        return jsonify({
            "ticket": ticket,
            "closed": None,
            "reason": "no deals found",
        })

    return jsonify({
        "ticket": ticket,
        "closed": True,
        "exit_price": float(out_deal.price),
        "pnl": float(out_deal.profit),
        "closed_at": datetime.fromtimestamp(out_deal.time, tz=timezone.utc).isoformat(),
    })


def _asset_class_for_symbol(symbol: str) -> str:
    """Dérive la classe d'asset depuis le symbole MT5 (EURUSD, XAUUSD, BTCUSD, etc.).

    Le radar passe par l'asset_class_for(pair) de config.settings ; ici on
    reproduit la même logique côté bridge sans importer le package radar.
    """
    s = (symbol or "").upper()
    if any(k in s for k in ("BTC", "ETH", "LTC", "XRP", "DOGE", "SOL", "ADA")):
        return "crypto"
    if any(k in s for k in ("XAU", "XAG", "GOLD", "SILVER", "PALL", "PLAT")):
        return "metal"
    if any(k in s for k in ("SPX", "NDX", "NAS", "DJ", "DAX", "FTSE", "NIKK", "CAC", "STOXX", "ASX")):
        return "equity_index"
    if any(k in s for k in ("WTI", "OIL", "BRENT", "USOIL", "UKOIL", "GAS")):
        return "energy"
    return "forex"


def _max_lot_for_symbol(symbol: str) -> float:
    """Retourne le cap effectif : min(MAX_LOT global, MAX_LOT_PER_CLASS[class])."""
    cls = _asset_class_for_symbol(symbol)
    class_cap = MAX_LOT_PER_CLASS.get(cls)
    if class_cap is None:
        return MAX_LOT
    return min(MAX_LOT, float(class_cap))


def _compute_lots_from_symbol(symbol: str, entry: float, sl: float, risk_money: float) -> float:
    """Sizing précis basé sur les specs RÉELLES du broker pour ce symbole.

    Utilise mt5.symbol_info() pour obtenir :
    - trade_contract_size : unités par lot (forex 100000, XAU 100, etc.)
    - point : taille d'un point (EURUSD=0.00001, XAU=0.01)
    - trade_tick_value : valeur en devise du compte d'un tick pour 1 lot
    - volume_min/max/step : bornes autorisées par le broker

    Formule :
        tick_size = point
        ticks_to_sl = distance / tick_size
        risk_per_lot = ticks_to_sl * tick_value
        lots = risk_money / risk_per_lot

    Tombe en 0.01 si le symbole est inconnu ou si les données sont corrompues.
    """
    info = mt5.symbol_info(symbol)
    if info is None:
        return 0.01
    distance = abs(entry - sl)
    if distance <= 0 or info.point <= 0:
        return 0.01
    ticks_to_sl = distance / info.point
    tick_value = info.trade_tick_value
    if tick_value <= 0:
        return 0.01
    risk_per_lot = ticks_to_sl * tick_value
    if risk_per_lot <= 0:
        return 0.01
    raw_lots = risk_money / risk_per_lot
    # Clamp sur les bornes broker + sur MAX_LOT interne
    step = info.volume_step or 0.01
    lots = round(raw_lots / step) * step
    lots = max(info.volume_min or 0.01, min(info.volume_max or 100.0, lots))
    lots = min(_max_lot_for_symbol(symbol), lots)
    return round(lots, 2)


@app.route("/order", methods=["POST"])
@require_api_key
def place_order():
    """Reçoit un trade_setup et le place (PAPER ou LIVE selon PAPER_MODE).

    Payload JSON attendu (deux modes de sizing possibles) :

    Mode A — lots explicites fournis par le client :
        { "pair": "EUR/USD", "direction": "buy", "entry": ..., "sl": ...,
          "tp": ..., "lots": 0.05, "comment": "..." }

    Mode B — risque ciblé (le bridge calcule les lots selon les specs broker) :
        { "pair": "EUR/USD", "direction": "buy", "entry": ..., "sl": ...,
          "tp": ..., "risk_money": 100, "comment": "..." }

    Si les deux sont présents, risk_money gagne (calcul précis).
    Si aucun n'est présent, erreur 400.
    """
    data = request.get_json(silent=True) or {}

    # ─── Validation des champs de base ────────────────────────────
    for field in ("pair", "direction", "entry", "sl", "tp"):
        if field not in data:
            return jsonify({"error": f"missing field: {field}"}), 400
    if "lots" not in data and "risk_money" not in data:
        return jsonify({
            "error": "one of 'lots' or 'risk_money' is required"
        }), 400

    direction = str(data["direction"]).lower()
    if direction not in ("buy", "sell"):
        return jsonify({"error": "direction must be 'buy' or 'sell'"}), 400

    try:
        entry = float(data["entry"])
        sl = float(data["sl"])
        tp = float(data["tp"])
    except (ValueError, TypeError):
        return jsonify({"error": "entry/sl/tp must be numeric"}), 400

    # Cohérence SL/TP selon la direction — vérifié avant sizing pour fail fast
    if direction == "buy" and not (sl < entry < tp):
        return jsonify({"error": "BUY: expected sl < entry < tp"}), 400
    if direction == "sell" and not (tp < entry < sl):
        return jsonify({"error": "SELL: expected tp < entry < sl"}), 400

    # ─── MT5 ──────────────────────────────────────────────────────
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503

    pair = data["pair"]
    mt5_symbol = resolve_symbol(pair)
    if not mt5_symbol:
        return jsonify({
            "error": f"No MT5 symbol found for {pair}. "
                     f"Try /symbols to see what's available on {MT5_SERVER}."
        }), 404

    # ─── Sizing : lots explicites OU calcul depuis risk_money ────
    if "risk_money" in data:
        try:
            risk_money = float(data["risk_money"])
        except (ValueError, TypeError):
            return jsonify({"error": "risk_money must be numeric"}), 400
        if risk_money <= 0:
            return jsonify({"error": "risk_money must be > 0"}), 400
        lots = _compute_lots_from_symbol(mt5_symbol, entry, sl, risk_money)
        sizing_mode = "risk-based"
    else:
        try:
            lots = float(data["lots"])
        except (ValueError, TypeError):
            return jsonify({"error": "lots must be numeric"}), 400
        sizing_mode = "explicit"

    # ─── Garde-fous lots ──────────────────────────────────────────
    if lots <= 0:
        return jsonify({"error": f"lots must be > 0 (got {lots})"}), 400
    effective_max = _max_lot_for_symbol(mt5_symbol)
    if lots > effective_max:
        return jsonify({
            "error": f"lots {lots} > cap {effective_max} for {mt5_symbol} "
                     f"(class={_asset_class_for_symbol(mt5_symbol)}, "
                     f"MAX_LOT global={MAX_LOT})"
        }), 400

    log_prefix = "[PAPER]" if PAPER_MODE else "[LIVE]"
    logger.info(
        f"{log_prefix} {direction.upper()} {lots} {mt5_symbol} "
        f"entry={entry} sl={sl} tp={tp} "
        f"sizing={sizing_mode} "
        f"comment={data.get('comment', '')}"
    )

    client_comment = data.get("comment", "")

    if PAPER_MODE:
        _db_log_order(
            mode="paper", status="paper", pair=pair, symbol=mt5_symbol,
            direction=direction, lots=lots, entry=entry, sl=sl, tp=tp,
            risk_money=data.get("risk_money"), confidence=data.get("confidence"), client_comment=client_comment,
            message="PAPER_MODE=true",
        )
        return jsonify({
            "ok": True,
            "mode": "paper",
            "message": "Ordre simulé uniquement. PAPER_MODE=true dans .env.",
            "sizing_mode": sizing_mode,
            "echo": {
                "pair": pair, "resolved_symbol": mt5_symbol, "direction": direction,
                "entry": entry, "sl": sl, "tp": tp, "lots": lots,
                "comment": client_comment,
            },
        })

    # ─── LIVE mode ──────────────────────────────────────────────
    try:
        return _handle_live_order(
            data=data, pair=pair, mt5_symbol=mt5_symbol, direction=direction,
            lots=lots, entry=entry, sl=sl, tp=tp, sizing_mode=sizing_mode,
            client_comment=client_comment,
        )
    except Exception as e:
        logger.exception(f"LIVE order exception: {e}")
        _db_log_order(
            mode="live", status="error", pair=pair, symbol=mt5_symbol,
            direction=direction, lots=lots, entry=entry, sl=sl, tp=tp,
            risk_money=data.get("risk_money"), confidence=data.get("confidence"), client_comment=client_comment,
            message=f"Python exception: {type(e).__name__}: {e}"[:500],
        )
        return jsonify({
            "ok": False, "mode": "live",
            "error": f"{type(e).__name__}: {e}",
        }), 500


def _handle_live_order(*, data, pair, mt5_symbol, direction, lots, entry, sl, tp, sizing_mode, client_comment):
    """Extrait de place_order pour isoler les exceptions LIVE dans un try/except."""
    ok_gate, reason = _check_safety_gates(mt5_symbol, direction)
    if not ok_gate:
        logger.warning(f"[LIVE BLOCKED] {reason}")
        _db_log_order(
            mode="live", status="blocked", pair=pair, symbol=mt5_symbol,
            direction=direction, lots=lots, entry=entry, sl=sl, tp=tp,
            risk_money=data.get("risk_money"), confidence=data.get("confidence"), client_comment=client_comment,
            message=reason,
        )
        return jsonify({"ok": False, "blocked": True, "reason": reason}), 429

    result = _send_market_order(mt5_symbol, direction, lots, sl, tp, comment=client_comment or "scalping-radar")

    if result["ok"]:
        logger.info(
            f"[LIVE ✓] ticket #{result['ticket']} {direction} {result['volume']} "
            f"{mt5_symbol} @ {result['price']} SL={sl} TP={tp}"
        )
        # Mémorise TP1/TP2 pour le partial close + trailing dans le monitor.
        tp2_val = data.get("tp2")
        try:
            tp2_float = float(tp2_val) if tp2_val else None
        except (ValueError, TypeError):
            tp2_float = None
        _register_position_meta(result["ticket"], tp1=tp, tp2=tp2_float)
        _db_log_order(
            mode="live", status="filled", pair=pair, symbol=mt5_symbol,
            direction=direction, lots=result["volume"],
            entry=result["price"], sl=sl, tp=tp,
            risk_money=data.get("risk_money"), confidence=data.get("confidence"),
            ticket=result["ticket"], retcode=result["retcode"],
            message=result["message"], client_comment=client_comment,
        )
        return jsonify({
            "ok": True, "mode": "live",
            "ticket": result["ticket"], "price": result["price"],
            "volume": result["volume"],
            "sizing_mode": sizing_mode,
            "tp2_tracked": tp2_float is not None,
        })
    else:
        logger.error(
            f"[LIVE REJECTED] {direction} {mt5_symbol} retcode={result.get('retcode')} "
            f"msg={result.get('message')}"
        )
        _db_log_order(
            mode="live", status="rejected", pair=pair, symbol=mt5_symbol,
            direction=direction, lots=lots, entry=entry, sl=sl, tp=tp,
            risk_money=data.get("risk_money"), confidence=data.get("confidence"),
            retcode=result.get("retcode"), message=result.get("message"),
            client_comment=client_comment,
        )
        return jsonify({
            "ok": False, "mode": "live",
            "retcode": result.get("retcode"),
            "message": result.get("message"),
        }), 500


@app.route("/audit", methods=["GET"])
@require_api_key
def audit():
    """Liste les ordres enregistrés en DB.

    Query params :
    - limit : max lignes (défaut 50, max 500)
    - since_id : ne retourne que les id > since_id (ordre croissant, pour sync
      incrémentale côté backend Scalping-Radar)
    - status : filtre sur status ('filled', 'closed', 'rejected', 'paper', ...)
    """
    try:
        limit = min(500, int(request.args.get("limit", "50")))
    except ValueError:
        limit = 50
    since_id = request.args.get("since_id")
    status = request.args.get("status")
    try:
        with sqlite3.connect(_DB_PATH) as conn:
            conn.row_factory = sqlite3.Row
            where = []
            params = []
            if since_id is not None:
                try:
                    where.append("id > ?")
                    params.append(int(since_id))
                except ValueError:
                    pass
            if status:
                where.append("status = ?")
                params.append(status)
            where_sql = ("WHERE " + " AND ".join(where)) if where else ""
            # Si since_id fourni : ordre croissant (pour que le backend sache
            # le dernier id traité). Sinon ordre décroissant (UI humain).
            order_sql = "ORDER BY id ASC" if since_id else "ORDER BY id DESC"
            params.append(limit)
            rows = conn.execute(
                f"SELECT * FROM orders {where_sql} {order_sql} LIMIT ?",
                params,
            ).fetchall()
            return jsonify({
                "count": len(rows),
                "orders": [dict(r) for r in rows],
            })
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/kill", methods=["POST"])
@require_api_key
def kill_switch():
    """Ferme toutes les positions ouvertes immédiatement.

    Respecte PAPER_MODE : en paper, retourne seulement la liste simulée.
    """
    if not ensure_mt5_connected():
        return jsonify({"error": "MT5 not connected"}), 503

    pos_list = mt5.positions_get() or []
    if not pos_list:
        return jsonify({"closed": [], "message": "No open positions"})

    if PAPER_MODE:
        logger.warning(
            f"[PAPER KILL] Aurait fermé {len(pos_list)} position(s) : "
            f"{[p.ticket for p in pos_list]}"
        )
        return jsonify({
            "mode": "paper",
            "would_close": [p.ticket for p in pos_list],
        })

    # LIVE : envoie un ordre opposite sur chaque position
    results = []
    for p in pos_list:
        r = _close_position(p)
        results.append(r)
        _db_log_order(
            mode="live",
            status="filled" if r.get("ok") else "rejected",
            symbol=p.symbol,
            direction="close-" + ("sell" if p.type == mt5.POSITION_TYPE_BUY else "buy"),
            lots=p.volume,
            ticket=p.ticket,
            retcode=r.get("retcode"),
            message=f"KILL: {r.get('message')}",
            client_comment="kill-switch",
        )
    ok = sum(1 for r in results if r.get("ok"))
    logger.warning(f"[LIVE KILL] fermé {ok}/{len(results)} position(s)")
    return jsonify({"mode": "live", "total": len(results), "ok": ok, "results": results})


# ─── Démarrage ──────────────────────────────────────────────────────

def main():
    _db_init()
    logger.info("=" * 60)
    logger.info(f"Bridge MT5 démarrage")
    logger.info(f"  MT5 Python package : {mt5.__version__}")
    logger.info(f"  Compte              : {MT5_LOGIN}@{MT5_SERVER}")
    logger.info(f"  PAPER_MODE          : {PAPER_MODE}")
    logger.info(f"  MAX_LOT             : {MAX_LOT}")
    logger.info(f"  Listen              : http://{LISTEN_HOST}:{LISTEN_PORT}")
    logger.info(f"  MAX_DAILY_LOSS_PCT  : {MAX_DAILY_LOSS_PCT}%")
    logger.info(f"  MAX_OPEN_POSITIONS  : {MAX_OPEN_POSITIONS}")
    logger.info(f"  DEDUP_WINDOW_SEC    : {DEDUP_WINDOW_SEC}")
    logger.info(f"  TRADING_HOURS_UTC   : {TRADING_HOURS_UTC or '(toujours)'}")
    logger.info(f"  Audit DB            : {_DB_PATH}")
    if _KEY_AUTOGENERATED:
        logger.warning("=" * 60)
        logger.warning(f"BRIDGE_API_KEY généré automatiquement :")
        logger.warning(f"    {BRIDGE_API_KEY}")
        logger.warning("Copie-le dans .env (BRIDGE_API_KEY=...) pour le garder stable.")
        logger.warning("=" * 60)

    # Test de connexion à MT5 au démarrage — échec rapide si MT5 fermé
    if not ensure_mt5_connected():
        logger.error(
            "Impossible de se connecter à MT5 Desktop. Vérifier que :\n"
            "  1. MT5 Desktop Windows est lancé et affiche le compte.\n"
            "  2. Login/password/server dans .env sont corrects.\n"
            "  3. Aucun autre script n'utilise déjà la session MT5."
        )
        # On continue quand même (pour que /health réponde et dise pourquoi)

    # Démarre le monitor de positions (break-even auto)
    monitor_thread = threading.Thread(
        target=_position_monitor_loop, name="position-monitor", daemon=True
    )
    monitor_thread.start()

    try:
        app.run(host=LISTEN_HOST, port=LISTEN_PORT, debug=False)
    finally:
        _monitor_stop.set()
        monitor_thread.join(timeout=3)


if __name__ == "__main__":
    main()
